config/routes.rb
Rails.application.routes.draw do
  get 'product/show', to: 'product#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'product#index'
  get 'product/index', to: 'product#index'
  post 'product/upload', to: 'product#upload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @product = Product.new
  end

  def show
    @product = Product.find(1)
  end

  def upload
    @product = Product.new(product_params)
    @product.save
  end

  def upload_image
    params[:file]
  end

  def product_params
    params.require(:product).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/_form.html.erb
<%= form_for(@product, url: product_upload_path) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  </div>
  <div class="field">
  </div>
  <!-- 追加箇所 開始 -->
  <div class="field">
    <% if @product.image? %>
      <div class="thumbnail">
        <%= image_tag @product.image.url %>
      </div>
    <% end %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @product.persisted? && @product.image? %>
      <label>
        <%= f.check_box :remove_image %>
        画像を削除
      </label>
    <% end %>
  </div>
  <!-- 追加箇所 終了 -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_tag(product_upload_path, class: 'dropzone', id: 'upload-dropzone') do %>
  <div class="fallback">
    <%= file_field_tag('attach[image]') %>
  </div>
<% end %>

app/views/product/index.html.erb
<h1>Product#index</h1>
<p>Find me in app/views/product/index.html.erb</p>
<%= render 'form' %>

app/views/product/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
</p>

<p>
  <strong>Price:</strong>
</p>

<!-- 追加箇所 開始 -->
<p>
  <strong>Image:</strong>
  <% if @product.image? %>
    <div class="thumbnail">
      <%= image_tag @product.image.url %>
    </div>
  <% end %>
</p>
<!-- 追加箇所 終了 -->